In [1]:
import pandas as pd

In [4]:
dataset_centroid = pd.read_parquet("../data/processed/04_centroid_drift/centroid_drift_wpz_neighbors.parquet")
dataset_gaussian = pd.read_parquet("../data/processed/06_gaussian_distribution_drift/gaussian_w2_drift_wpz_neighbors.parquet")

In [5]:
dataset_centroid

,modality,genre,window_start,window_end,next_window_start,next_window_end,window_gap,n_tracks_t,n_tracks_t1,cosine_similarity,cosine_distance
0,essentia,alternative metal,1995,1999,1996,2000,1,21,22,0.958763,0.041237
1,essentia,alternative metal,1996,2000,1997,2001,1,22,34,0.948263,0.051737
2,essentia,alternative metal,1997,2001,1998,2002,1,34,51,0.960931,0.039069
3,essentia,alternative metal,1998,2002,1999,2003,1,51,44,0.985195,0.014805
4,essentia,alternative metal,1999,2003,2000,2004,1,44,39,0.995410,0.004590
...,...,...,...,...,...,...,...,...,...,...,...
18263,vgg19,witch house,2012,2016,2013,2017,1,38,40,0.925999,0.074001
18264,vgg19,witch house,2013,2017,2014,2018,1,40,38,0.884608,0.115392
18265,vgg19,witch house,2014,2018,2015,2019,1,38,30,0.967716,0.032284
18266,vgg19,worship,2014,2018,2015,2019,1,25,27,0.976466,0.023534
18267,vgg19,worship,2015,2019,2016,2020,1,27,22,0.939128,0.060872

In [6]:
dataset_gaussian

,modality,genre,window_start,window_end,next_window_start,next_window_end,window_gap,n_tracks_t,n_tracks_t1,w2_distance,w2_squared,mean_component,std_component
0,essentia,alternative metal,1997,2001,1998,2002,1,34,51,13.582441,184.482690,3.446403,13.137922
1,essentia,alternative metal,1998,2002,1999,2003,1,51,44,6.074669,36.901601,2.795829,5.393045
2,essentia,alternative metal,1999,2003,2000,2004,1,44,39,2.794587,7.809717,1.699129,2.218711
3,essentia,alternative metal,2000,2004,2001,2005,1,39,59,7.128377,50.813760,4.045676,5.869094
4,essentia,alternative metal,2001,2005,2002,2006,1,59,56,6.359724,40.446092,2.492853,5.850793
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14908,vgg19,witch house,2010,2014,2011,2015,1,37,42,17.044219,290.505416,9.488844,14.158646
14909,vgg19,witch house,2011,2015,2012,2016,1,42,38,9.711957,94.322106,5.931944,7.689873
14910,vgg19,witch house,2012,2016,2013,2017,1,38,40,13.788609,190.125751,8.074865,11.176865
14911,vgg19,witch house,2013,2017,2014,2018,1,40,38,16.826206,283.121215,10.897181,12.820790
14912,vgg19,witch house,2014,2018,2015,2019,1,38,30,11.271090,127.037466,7.440379,8.466299