#### imports

In [3]:
import pandas as pd
import os

#### load data

In [6]:
data_path = r"..\data"

#### mfcc

In [12]:
mfcc_path = data_path + r"\mfcc.csv"
mfcc_data = pd.read_csv(mfcc_path)
mfcc_data.head()

,id,MFCC000,MFCC001,MFCC002,MFCC003,MFCC004,MFCC005,MFCC006,MFCC007,MFCC008,...,cov_10_12,cov_11_11,cov_11_12,cov_12_12,genre,popularity,release,artist,song,album_name
0,9EPCgcAlXdgiFsx4,20.640961,-5.828413,-6.140859,2.526664,-1.409552,2.681575,-2.989035,6.298501,3.528709,...,-4.037570,120.298222,18.571392,84.858156,pop,36.0,2016,Tove Lo,Fairy Dust - Chapter I,Lady Wood
1,9epP1yOXfLKlkR3S,24.351542,-16.611490,-10.792922,0.983246,-4.003687,-0.180248,-1.510487,-0.663130,2.915891,...,2.551358,55.188890,18.194372,52.472903,rock,44.0,2008,Carolina Liar,I'm Not Over,Coming To Terms
2,9EPSUhPoRVOFU3WZ,20.963654,-10.754437,-17.771996,4.075799,-7.670935,7.884864,6.939635,-0.451056,1.786007,...,4.270046,92.649081,32.317742,94.037335,new wave,44.0,1989,The Cure,Fascination Street,Disintegration (Deluxe Edition)
3,9eQ9CI53RilCiWe1,23.706192,-6.617346,-0.802629,-7.173328,-7.087190,1.222832,0.271057,5.402615,-1.984503,...,-0.670753,92.840371,31.832446,80.958201,singer-songwriter,39.0,2015,Tiago Iorc,Sol Que Faltava,Troco Likes
4,9eQBXVI9m9OVpOzk,23.435280,-15.198643,-15.216316,6.386479,-1.970684,2.223027,3.663818,10.492731,3.448581,...,-10.117312,70.432960,14.377084,68.796059,indie rock,28.0,2018,Tokyo Police Club,Gone,10 Years of Mom+Pop

In [15]:
mfcc_data.shape

(109269, 111)

#### music_nn

In [13]:
musicnn_path = data_path + r"\musicnn.csv"
musicnn_data = pd.read_csv(musicnn_path)
musicnn_data.head()

,id,0,1,2,3,4,5,6,7,8,...,46,47,48,49,genre,popularity,release,artist,song,album_name
0,0009fFIM1eYThaPg,0.055225,0.001055,0.015216,0.301295,0.007372,0.121369,0.205030,0.114958,0.144303,...,0.008268,0.002438,0.104358,0.000896,pop,12.0,2009,Cheryl,Rain on Me,3 Words
1,0010xmHR6UICBOYT,0.090460,0.004675,0.244330,0.185277,0.006459,0.218079,0.271902,0.014446,0.021707,...,0.002906,0.000388,0.002674,0.000264,underground hip hop,46.0,2013,Oddisee,After Thoughts,The Beauty in All
2,002Jyd0vN4HyCpqL,0.249110,0.111420,0.023323,0.072560,0.146912,0.058966,0.073982,0.149235,0.251058,...,0.042284,0.019171,0.008823,0.001915,hard rock,31.0,1974,Blue Öyster Cult,ME 262,Secret Treaties
3,006TYKNjNxWjfKjy,0.195338,0.107382,0.101820,0.023141,0.109134,0.078777,0.034734,0.425358,0.043190,...,0.020245,0.057756,0.021381,0.006125,symphonic metal,33.0,2017,Rhapsody,Flames of Revenge,Legendary Years (Re-Recorded)
4,007LIJOPQ4Sb98qV,0.322574,0.006046,0.026422,0.009654,0.004463,0.136346,0.008123,0.804749,0.076759,...,0.006969,0.239036,0.002354,0.001209,post-punk,19.0,2009,The Chameleons,Nostalgia,What Does Anything Mean? Basically (2009 Remas...

In [16]:
musicnn_data.shape

(109268, 57)

#### word2vec

In [14]:
word2vec_path = data_path + r"\word2vec.csv"
word2vec_data = pd.read_csv(word2vec_path)
word2vec_data.head()

,id,0,1,2,3,4,5,6,7,8,...,296,297,298,299,genre,popularity,release,artist,song,album_name
0,710GxwapFWu6nZX9,0.012378,0.048408,0.001605,0.023883,-0.025053,0.004592,0.020611,-0.028692,0.040993,...,-0.012984,-0.014875,0.012971,-0.002531,punk,28.0,2018,Iceage,Broken Hours,Broken Hours
1,0LiOzxBZ1aPLlFsK,0.031109,0.018026,0.022785,0.028802,-0.026084,-0.006278,0.030599,-0.041043,0.036703,...,-0.009981,-0.027846,0.021100,-0.020994,rock,26.0,2012,Billy Talent,Cure For the Enemy,Dead Silence
2,JgqyXT3EFKz10FSz,0.027534,0.010042,0.010540,0.023234,-0.024125,0.000474,0.020764,-0.051780,0.023568,...,-0.004652,-0.015556,0.019013,-0.007545,singer-songwriter,28.0,2017,Mark Lanegan,Nocturne,Gargoyle
3,mxzw6q1VfWMdd9ro,0.013538,0.026949,0.006707,0.026687,-0.028433,-0.010083,0.022415,-0.040218,0.033329,...,0.016312,-0.021790,0.016149,-0.010693,garage rock,41.0,2008,Heartless Bastards,The Mountain,The Mountain
4,F4vPrkSvYHwgexdS,0.019174,0.025422,0.010472,0.029765,-0.015188,0.007465,0.025536,-0.030486,0.026359,...,-0.012303,-0.011325,0.008986,-0.021229,progressive metal,34.0,2013,Haken,Atlas Stone,The Mountain

In [17]:
word2vec_data.shape

(109269, 307)

#### vvg19

In [ ]:
vgg19_path = data_path + r"\vgg19.tsv.bz2"
df = pd.read_csv(vgg19_path, sep="\t", compression="bz2")